/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planner;

/**
 *
 * @author Mike
 */
public class FrameTemplate extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrameTemplate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        startDirectionGroup = new javax.swing.ButtonGroup();
        contentPanel = new javax.swing.JPanel();
        mapContainer = new javax.swing.JPanel();
        mapLabelContainer = new javax.swing.JPanel();
        mapLabel = new javax.swing.JLabel();
        mapPanel = new javax.swing.JPanel();
        controlsPanel = new javax.swing.JPanel();
        leftControlPanel = new javax.swing.JPanel();
        movePanel = new javax.swing.JPanel();
        moveLabel = new javax.swing.JLabel();
        moveTextField = new javax.swing.JTextField();
        moveBtn = new javax.swing.JButton();
        CalibrationPanel = new javax.swing.JPanel();
        calibrationLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        startDirectionGroupPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        northRadioButton = new javax.swing.JRadioButton();
        eastRadioButton = new javax.swing.JRadioButton();
        southRadioButton = new javax.swing.JRadioButton();
        westRadioButton = new javax.swing.JRadioButton();
        rotateControlPanel = new javax.swing.JPanel();
        topLeftSpacePanel = new javax.swing.JPanel();
        topRotatePanel = new javax.swing.JPanel();
        topRotateBtn = new javax.swing.JButton();
        topRightSpacePanel = new javax.swing.JPanel();
        leftRotatePanel = new javax.swing.JPanel();
        leftRotateBtn = new javax.swing.JButton();
        centerOrientationPanel = new javax.swing.JPanel();
        robotOrientationPanel = new javax.swing.JPanel();
        robotOrientationImage = new javax.swing.JLabel();
        rightRotatePanel = new javax.swing.JPanel();
        rightRotateBtn = new javax.swing.JButton();
        bottomLeftSpacePanel = new javax.swing.JPanel();
        bottomRotatePanel = new javax.swing.JPanel();
        bottomRotateBtn = new javax.swing.JButton();
        bottomRightSpacePanel = new javax.swing.JPanel();
        actionLogPanel = new javax.swing.JPanel();
        logLabelPanel = new javax.swing.JPanel();
        logLabel = new javax.swing.JLabel();
        logTextFieldPanel = new javax.swing.JPanel();
        activityLogScrollPane = new javax.swing.JScrollPane();
        activityLogTextArea = new javax.swing.JTextPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fmNewCalibrationProfileMenuItem = new javax.swing.JMenuItem();
        fmLoadCalibrationProfileMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Team N2 iRobot Front End");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setName("outsideFrame"); // NOI18N

        java.awt.GridBagLayout contentPanelLayout = new java.awt.GridBagLayout();
        contentPanelLayout.rowHeights = new int[] {0, 75};
        contentPanelLayout.columnWeights = new double[] {1.0};
        contentPanelLayout.rowWeights = new double[] {1.0};
        contentPanel.setLayout(contentPanelLayout);

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWeights = new double[] {1.0};
        mapContainer.setLayout(jPanel2Layout);

        mapLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mapLabel.setText("Playing Field");
        mapLabelContainer.add(mapLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        mapContainer.add(mapLabelContainer, gridBagConstraints);

        mapPanel.setBackground(new java.awt.Color(255, 255, 255));
        mapPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 788;
        gridBagConstraints.ipady = 404;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        mapContainer.add(mapPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contentPanel.add(mapContainer, gridBagConstraints);

        controlsPanel.setLayout(new java.awt.GridLayout(1, 3));

        movePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        moveLabel.setText("Linear Move (cm):");
        movePanel.add(moveLabel);

        moveTextField.setText("0");
        moveTextField.setMinimumSize(new java.awt.Dimension(35, 22));
        moveTextField.setName(""); // NOI18N
        moveTextField.setPreferredSize(new java.awt.Dimension(35, 22));
        moveTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveTextFieldActionPerformed(evt);
            }
        });
        movePanel.add(moveTextField);

        moveBtn.setText("Go");
        moveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBtnActionPerformed(evt);
            }
        });
        movePanel.add(moveBtn);

        CalibrationPanel.setLayout(new java.awt.GridLayout(2, 0));

        calibrationLabel.setText("Calibration Profile: \"BOT XX\"");
        CalibrationPanel.add(calibrationLabel);

        jLabel1.setText("Connection Status: CONNECTION_STATUS");
        CalibrationPanel.add(jLabel1);

        startDirectionGroupPanel.setLayout(new java.awt.GridLayout(5, 1));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Start Direction");
        jPanel1.add(jLabel2);

        startDirectionGroupPanel.add(jPanel1);

        startDirectionGroup.add(northRadioButton);
        northRadioButton.setText("North");
        startDirectionGroupPanel.add(northRadioButton);

        startDirectionGroup.add(eastRadioButton);
        eastRadioButton.setText("East");
        startDirectionGroupPanel.add(eastRadioButton);

        startDirectionGroup.add(southRadioButton);
        southRadioButton.setText("South");
        startDirectionGroupPanel.add(southRadioButton);

        startDirectionGroup.add(westRadioButton);
        westRadioButton.setText("West");
        startDirectionGroupPanel.add(westRadioButton);

        javax.swing.GroupLayout leftControlPanelLayout = new javax.swing.GroupLayout(leftControlPanel);
        leftControlPanel.setLayout(leftControlPanelLayout);
        leftControlPanelLayout.setHorizontalGroup(
            leftControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftControlPanelLayout.createSequentialGroup()
                .addGroup(leftControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CalibrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startDirectionGroupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftControlPanelLayout.setVerticalGroup(
            leftControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftControlPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(movePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalibrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startDirectionGroupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        controlsPanel.add(leftControlPanel);

        rotateControlPanel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout topLeftSpacePanelLayout = new javax.swing.GroupLayout(topLeftSpacePanel);
        topLeftSpacePanel.setLayout(topLeftSpacePanelLayout);
        topLeftSpacePanelLayout.setHorizontalGroup(
            topLeftSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topLeftSpacePanelLayout.setVerticalGroup(
            topLeftSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        rotateControlPanel.add(topLeftSpacePanel, new java.awt.GridBagConstraints());

        topRotateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cprefrontend/direction-arrow-up.png"))); // NOI18N
        topRotateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topRotateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topRotatePanelLayout = new javax.swing.GroupLayout(topRotatePanel);
        topRotatePanel.setLayout(topRotatePanelLayout);
        topRotatePanelLayout.setHorizontalGroup(
            topRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(topRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(topRotatePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(topRotateBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        topRotatePanelLayout.setVerticalGroup(
            topRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(topRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(topRotatePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(topRotateBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        rotateControlPanel.add(topRotatePanel, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout topRightSpacePanelLayout = new javax.swing.GroupLayout(topRightSpacePanel);
        topRightSpacePanel.setLayout(topRightSpacePanelLayout);
        topRightSpacePanelLayout.setHorizontalGroup(
            topRightSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topRightSpacePanelLayout.setVerticalGroup(
            topRightSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        rotateControlPanel.add(topRightSpacePanel, new java.awt.GridBagConstraints());

        leftRotateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cprefrontend/direction-arrow-left.png"))); // NOI18N
        leftRotateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftRotateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftRotatePanelLayout = new javax.swing.GroupLayout(leftRotatePanel);
        leftRotatePanel.setLayout(leftRotatePanelLayout);
        leftRotatePanelLayout.setHorizontalGroup(
            leftRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftRotatePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(leftRotateBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        leftRotatePanelLayout.setVerticalGroup(
            leftRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftRotatePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(leftRotateBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        rotateControlPanel.add(leftRotatePanel, gridBagConstraints);

        robotOrientationPanel.setMinimumSize(new java.awt.Dimension(80, 80));

        robotOrientationImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cprefrontend/robot-orientation-north.png"))); // NOI18N

        javax.swing.GroupLayout robotOrientationPanelLayout = new javax.swing.GroupLayout(robotOrientationPanel);
        robotOrientationPanel.setLayout(robotOrientationPanelLayout);
        robotOrientationPanelLayout.setHorizontalGroup(
            robotOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(robotOrientationImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        robotOrientationPanelLayout.setVerticalGroup(
            robotOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(robotOrientationImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout centerOrientationPanelLayout = new javax.swing.GroupLayout(centerOrientationPanel);
        centerOrientationPanel.setLayout(centerOrientationPanelLayout);
        centerOrientationPanelLayout.setHorizontalGroup(
            centerOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerOrientationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(robotOrientationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        centerOrientationPanelLayout.setVerticalGroup(
            centerOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerOrientationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(robotOrientationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        rotateControlPanel.add(centerOrientationPanel, gridBagConstraints);

        rightRotateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cprefrontend/direction-arrow-right.png"))); // NOI18N
        rightRotateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightRotateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightRotatePanelLayout = new javax.swing.GroupLayout(rightRotatePanel);
        rightRotatePanel.setLayout(rightRotatePanelLayout);
        rightRotatePanelLayout.setHorizontalGroup(
            rightRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(rightRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightRotatePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(rightRotateBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        rightRotatePanelLayout.setVerticalGroup(
            rightRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(rightRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightRotatePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(rightRotateBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        rotateControlPanel.add(rightRotatePanel, gridBagConstraints);

        javax.swing.GroupLayout bottomLeftSpacePanelLayout = new javax.swing.GroupLayout(bottomLeftSpacePanel);
        bottomLeftSpacePanel.setLayout(bottomLeftSpacePanelLayout);
        bottomLeftSpacePanelLayout.setHorizontalGroup(
            bottomLeftSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bottomLeftSpacePanelLayout.setVerticalGroup(
            bottomLeftSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        rotateControlPanel.add(bottomLeftSpacePanel, gridBagConstraints);

        bottomRotateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cprefrontend/direction-arrow-down.png"))); // NOI18N
        bottomRotateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottomRotateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomRotatePanelLayout = new javax.swing.GroupLayout(bottomRotatePanel);
        bottomRotatePanel.setLayout(bottomRotatePanelLayout);
        bottomRotatePanelLayout.setHorizontalGroup(
            bottomRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(bottomRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottomRotatePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bottomRotateBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        bottomRotatePanelLayout.setVerticalGroup(
            bottomRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(bottomRotatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottomRotatePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bottomRotateBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        rotateControlPanel.add(bottomRotatePanel, gridBagConstraints);

        javax.swing.GroupLayout bottomRightSpacePanelLayout = new javax.swing.GroupLayout(bottomRightSpacePanel);
        bottomRightSpacePanel.setLayout(bottomRightSpacePanelLayout);
        bottomRightSpacePanelLayout.setHorizontalGroup(
            bottomRightSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bottomRightSpacePanelLayout.setVerticalGroup(
            bottomRightSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        rotateControlPanel.add(bottomRightSpacePanel, gridBagConstraints);

        controlsPanel.add(rotateControlPanel);

        logLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logLabel.setText("Robot Activity Log");
        logLabelPanel.add(logLabel);

        activityLogScrollPane.setViewportView(activityLogTextArea);

        javax.swing.GroupLayout logTextFieldPanelLayout = new javax.swing.GroupLayout(logTextFieldPanel);
        logTextFieldPanel.setLayout(logTextFieldPanelLayout);
        logTextFieldPanelLayout.setHorizontalGroup(
            logTextFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logTextFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityLogScrollPane))
        );
        logTextFieldPanelLayout.setVerticalGroup(
            logTextFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activityLogScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout actionLogPanelLayout = new javax.swing.GroupLayout(actionLogPanel);
        actionLogPanel.setLayout(actionLogPanelLayout);
        actionLogPanelLayout.setHorizontalGroup(
            actionLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logTextFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionLogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
        );
        actionLogPanelLayout.setVerticalGroup(
            actionLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionLogPanelLayout.createSequentialGroup()
                .addComponent(logLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logTextFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlsPanel.add(actionLogPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        contentPanel.add(controlsPanel, gridBagConstraints);

        fileMenu.setText("File");

        fmNewCalibrationProfileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        fmNewCalibrationProfileMenuItem.setText("New Calibration Profile");
        fmNewCalibrationProfileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmNewCalibrationProfileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fmNewCalibrationProfileMenuItem);

        fmLoadCalibrationProfileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        fmLoadCalibrationProfileMenuItem.setText("Load Calibration Profile");
        fmLoadCalibrationProfileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmLoadCalibrationProfileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fmLoadCalibrationProfileMenuItem);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem3.setText("jMenuItem3");
        fileMenu.add(jMenuItem3);
        fileMenu.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 683, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveTextFieldActionPerformed

    private void fmLoadCalibrationProfileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmLoadCalibrationProfileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmLoadCalibrationProfileMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void topRotateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topRotateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topRotateBtnActionPerformed

    private void rightRotateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightRotateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightRotateBtnActionPerformed

    private void bottomRotateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottomRotateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottomRotateBtnActionPerformed

    private void leftRotateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftRotateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftRotateBtnActionPerformed

    private void moveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveBtnActionPerformed

    private void fmNewCalibrationProfileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmNewCalibrationProfileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmNewCalibrationProfileMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTemplate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalibrationPanel;
    private javax.swing.JPanel actionLogPanel;
    private javax.swing.JScrollPane activityLogScrollPane;
    private javax.swing.JTextPane activityLogTextArea;
    private javax.swing.JPanel bottomLeftSpacePanel;
    private javax.swing.JPanel bottomRightSpacePanel;
    private javax.swing.JButton bottomRotateBtn;
    private javax.swing.JPanel bottomRotatePanel;
    private javax.swing.JLabel calibrationLabel;
    private javax.swing.JPanel centerOrientationPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JRadioButton eastRadioButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fmLoadCalibrationProfileMenuItem;
    private javax.swing.JMenuItem fmNewCalibrationProfileMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel leftControlPanel;
    private javax.swing.JButton leftRotateBtn;
    private javax.swing.JPanel leftRotatePanel;
    private javax.swing.JLabel logLabel;
    private javax.swing.JPanel logLabelPanel;
    private javax.swing.JPanel logTextFieldPanel;
    private javax.swing.JPanel mapContainer;
    private javax.swing.JLabel mapLabel;
    private javax.swing.JPanel mapLabelContainer;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton moveBtn;
    private javax.swing.JLabel moveLabel;
    private javax.swing.JPanel movePanel;
    private javax.swing.JTextField moveTextField;
    private javax.swing.JRadioButton northRadioButton;
    private javax.swing.JButton rightRotateBtn;
    private javax.swing.JPanel rightRotatePanel;
    private javax.swing.JLabel robotOrientationImage;
    private javax.swing.JPanel robotOrientationPanel;
    private javax.swing.JPanel rotateControlPanel;
    private javax.swing.JRadioButton southRadioButton;
    private javax.swing.ButtonGroup startDirectionGroup;
    private javax.swing.JPanel startDirectionGroupPanel;
    private javax.swing.JPanel topLeftSpacePanel;
    private javax.swing.JPanel topRightSpacePanel;
    private javax.swing.JButton topRotateBtn;
    private javax.swing.JPanel topRotatePanel;
    private javax.swing.JRadioButton westRadioButton;
    // End of variables declaration//GEN-END:variables
}
